apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mydomain-tls-cert
spec:
  dnsNames:
    - "mydomain.com"
    - "*.mydomain.com"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cluster-issuer
  secretName: mydomain-tls-cert
  duration: 2160h
  renewBefore: 94h