apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: postgresql-cred
    creationPolicy: Owner
  data:
  - secretKey: postgres-user
    remoteRef:
      key: postgresql
      property: dbuser
  - secretKey: postgres-password
    remoteRef:
      key: postgresql
      property: dbpassword
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
spec:
  storageClassName: gp3
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-02243161e6829f081
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
spec:
  storageClassName: gp3
  volumeName: postgresql-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi