apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
spec:
  storageClassName: gp3
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-03fe2801967ce0f0b
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
spec:
  storageClassName: gp3
  volumeName: rabbitmq-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

