apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: system
spec:
  template:
    metadata:
      labels:
        nodegroup: system
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t", "m", "r", "c"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["1", "2", "4"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-2a", "us-east-2b", "us-east-2c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values: ["nano", "micro", "small"]
  disruption:
    consolidationPolicy: WhenUnderutilized
  weight: 10
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: monitoring
spec:
  template:
    metadata:
      labels:
        nodegroup: monitoring
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t", "m", "r", "c"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["1", "2", "4"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-2a", "us-east-2b", "us-east-2c"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values: ["nano", "micro", "small"]
  disruption:
    consolidationPolicy: WhenUnderutilized
  weight: 10
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: tools
spec:
  template:
    metadata:
      labels:
        nodegroup: tools
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t", "m", "r", "c"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["1", "2", "4"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-2a", "us-east-2b", "us-east-2c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values: ["nano", "micro", "small"]
  disruption:
    consolidationPolicy: WhenUnderutilized
  weight: 10
