apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-cert-acm
rules:
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
- apiGroups:
    - "cert-manager.io"
  resources:
    - certificates
  verbs:
    - get