apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-a-problem.opsgenie: ArgoCD
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: 
      prune: true
      selfHeal: true
  project: monitoring
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: grafana-loki
    targetRevision: 4.6.6
    helm:
      values: |-
        promtail:
          resourcesPreset: "nano"
          
        gateway:
          nodeSelector:
            nodegroup: monitoring

        compactor:
          nodeSelector:
            nodegroup: monitoring

        distributor:
          nodeSelector:
            nodegroup: monitoring

        querier:
          nodeSelector:
            nodegroup: monitoring
          persistence:
            size: 5Gi

        queryFrontend:
          nodeSelector:
            nodegroup: monitoring

        memcachedchunks:
          nodeSelector:
            nodegroup: monitoring

        memcachedfrontend:
          nodeSelector:
            nodegroup: monitoring

        ingester:
          nodeSelector:
            nodegroup: monitoring
          persistence:
            size: 5Gi

        loki:
          nodeSelector:
            nodegroup: monitoring
          configuration: |
            auth_enabled: false
            server:
              http_listen_port: {{ .Values.loki.containerPorts.http }}
              grpc_listen_port: {{ .Values.loki.containerPorts.grpc }}
            common:
              compactor_address: http://{{ include "grafana-loki.compactor.fullname" . }}:{{ .Values.compactor.service.ports.http }}

            distributor:
              ring:
                kvstore:
                  store: memberlist

            memberlist:
              join_members:
                - {{ include "grafana-loki.gossip-ring.fullname" . }}

            ingester:
              lifecycler:
                ring:
                  kvstore:
                    store: memberlist
                  replication_factor: 1
              chunk_idle_period: 30m
              chunk_block_size: 262144
              chunk_encoding: snappy
              chunk_retain_period: 1m
              wal:
                dir: {{ .Values.loki.dataDir }}/wal

            limits_config:
              retention_period: 336h
              reject_old_samples: true
              reject_old_samples_max_age: 168h
              max_cache_freshness_per_query: 10m
              split_queries_by_interval: 15m
              allow_structured_metadata: true

            schema_config:
              configs:
              - from: 2020-10-24
                store: boltdb-shipper
                object_store: s3
                schema: v11
                index:
                  prefix: index_
                  period: 24h
              - from: 2024-03-12
                store: tsdb
                object_store: s3
                schema: v12
                index:
                  period: 24h
                  prefix: index_
              - from: 2024-04-23
                object_store: s3
                store: tsdb
                schema: v13
                index:
                  prefix: index_
                  period: 24h

            storage_config:
              aws:
                s3: http://minio.tools.svc.cluster.local:9000/grafana-loki
                region: us-east-2
                access_key_id: minio
                secret_access_key: KlaXR0AsaeAZQHUJAYzZuApEpRIO8OLPyMSuC8aB
                s3forcepathstyle: true
              boltdb_shipper:
                active_index_directory: {{ .Values.loki.dataDir }}/loki/index
                cache_location: {{ .Values.loki.dataDir }}/loki/cache
                cache_ttl: 168h
              tsdb_shipper:
                active_index_directory: {{ .Values.loki.dataDir }}/loki/tsdb-index
                cache_location: {{ .Values.loki.dataDir }}/loki/tsdb-cache

            query_scheduler:
              max_outstanding_requests_per_tenant: 32768

            querier:
              max_concurrent: 16

            chunk_store_config:
              {{- if .Values.memcachedchunks.enabled }}
              chunk_cache_config:
                memcached:
                  batch_size: 100
                  parallelism: 100
                memcached_client:
                  consistent_hash: true
                  addresses: dns+{{ include "grafana-loki.memcached-chunks.host" . }}
              {{- end }}
              {{- if .Values.memcachedindexwrites.enabled }}
              write_dedupe_cache_config:
                memcached:
                  batch_size: 100
                  parallelism: 100
                memcached_client:
                  consistent_hash: true
                  addresses: dns+{{ include "grafana-loki.memcached-index-writes.host" . }}
              {{- end }}

            table_manager:
              retention_deletes_enabled: false
              retention_period: 24h

            query_range:
              align_queries_with_step: true
              max_retries: 5
              cache_results: true
              results_cache:
                cache:
                  {{- if .Values.memcachedfrontend.enabled }}
                  memcached_client:
                    consistent_hash: true
                    addresses: dns+{{ include "grafana-loki.memcached-frontend.host" . }}
                    max_idle_conns: 16
                    timeout: 500ms
                    update_interval: 1m
                  {{- else }}
                  embedded-cache:
                    enabled: true
                    max_size_items: 1024
                    validity: 24h
                  {{- end }}
            {{- if not .Values.queryScheduler.enabled }}
            frontend_worker:
              frontend_address: grafana-loki-query-frontend-headless:9095
            {{- end }}

            frontend:
              log_queries_longer_than: 5s
              compress_responses: true
              tail_proxy_url: http://grafana-loki-querier:3100

            compactor:
              working_directory: {{ .Values.loki.dataDir }}/loki/retention
              compaction_interval: 10m
              retention_enabled: true
              retention_delete_delay: 2h
              retention_delete_worker_count: 150
              delete_request_store: s3
                  


      
