apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-alertmanager
  namespace: argocd
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=false
    automated:
      prune: true
      selfHeal: true
  source:
    chart: alertmanager
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 1.12.0
    helm:
      values: |
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
        podDisruptionBudget:
          minAvailable: 0
        config:
          receivers:
            - name: opsgenie
              opsgenie_configs:
              - api_key: ""
                send_resolved: true
                message: '{{.Alerts.Firing | len}} alert(s) firing'
                source: 'Prometheus'
          route:
            receiver: opsgenie
            routes:
            - receiver: 'opsgenie'
              match:
                severity: 'critical'

        nodeSelector:
          nodegroup: monitoring
        persistence:
          enabled: false